CREATE TABLE tb_weather (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR(255) NOT NULL,
    temperature DOUBLE PRECISION,
    description VARCHAR(255),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_weather PRIMARY KEY (id),
    CONSTRAINT uk_tb_weather_city UNIQUE (city)
);