spring.application.name=weather-app

# Schema Auto-Generation
# TO LEARN: NEVER use this in production. 
# The Schema Auto-Generation is a feature that is used to create the database schema automatically and it's not a good practice to use it in production because it can cause data loss.
# The good-practice is to use the Schema Management Tool like Flyway or Liquibase to manage the database schema.
spring.jpa.hibernate.ddl-auto=update


# Shows the SQL that the Hibernate is generating
spring.jpa.show-sql=true