spring.application.name=weather-app

# DATABASE (Injected via Docker Compose)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# HIBERNATE / JPA:
# TO LEARN: The Schema Auto-Generation is a feature that is used to create the database schema automatically. NEVER use `update` option in production. It's not a good practice to use it in production because it can cause data loss.
# The good-practice is to use the Schema Management Tool like Flyway or Liquibase to manage the database schema.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Ensures that the Hibernate waits for the Flyway to create the tables before trying to validate them:
spring.jpa.properties.hibernate.validator.apply_to_ddl=false



# FLYWAY:
# Explicitly enables the Flyway to avoid using the Schema Auto-Generation feature:
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# Explicitly ensures the path to the migrations folder:
spring.flyway.locations=classpath:db/migration
# Forces the Spring to set the Flyway migration cycle as priority over the DataSource
spring.flyway.baseline-on-migrate=true